CREATE TABLE UsersTable(user_id VARCHAR(100),name VARCHAR(200),email VARCHAR(200) UNIQUE,password VARCHAR(200),role VARCHAR(10) 
DEFAULT 'User',isassigned VARCHAR(10) DEFAULT '0',project_id VARCHAR(100) DEFAULT '0')

ALTER TABLE UsersTable ADD issent VARCHAR(10) DEFAULT '0'