-- CREATE TABLE UsersTable(user_id VARCHAR(100),name VARCHAR(200),email VARCHAR(200) UNIQUE,password VARCHAR(200),role VARCHAR(10) 
-- DEFAULT 'User',isassigned VARCHAR(10) DEFAULT '0',project_id VARCHAR(100) DEFAULT '0')

-- ALTER TABLE UsersTable ADD issent VARCHAR(10) DEFAULT '0'
-- ALTER TABLE UsersTable 
-- ALTER COLUMN user_id VARCHAR(100) NOT NULL
-- ALTER TABLE UsersTable ADD PRIMARY KEY (user_id)


-- NEW TABLE

CREATE TABLE UsersTable(user_id VARCHAR(100)PRIMARY KEY NOT NULL,name VARCHAR(200) NOT NULL,email VARCHAR(200) UNIQUE NOT NULL,password VARCHAR(200)NOT NULL,role VARCHAR(10) 
DEFAULT 'User' NOT NULL,isassigned VARCHAR(10) DEFAULT '0',project_id VARCHAR(100) DEFAULT '0',issent VARCHAR(10) DEFAULT '0')